let data = {
   "ciudades":[
      {
         "id_ciudad":"6",
         "nombre_ciudad":"LA SERENA",
         "latitud":"-29.9264439",
         "longitud":"-71.2412639",
         "cota":"314",
         "cursos":[
            {
               "id_curso":"",
               "id_categoria":"",
               "nombre":"",
               "fecha_inicio":"",
               "requisitos":"",
               "modalidad":[
                  {
                     "id_modalidad":"",
                     "nombre":"express",
                     "precio":"100",
                     "fecha_inicio":"10/25/2017",
                     "fecha_fin":"10/28/2017",
                     "disponibilidad":10
                  }
               ]
            }
         ]
      },
      {
         "id_ciudad":"5",
         "nombre_ciudad":"ANTOFAGASTA",
         "latitud":"-23.6435973",
         "longitud":"-70.3901541",
         "cota":"46",
         "cursos":[
            {
               "id_curso":"",
               "id_categoria":"",
               "nombre":"",
               "fecha_inicio":"",
               "requisitos":"",
               "modalidad":[
                  {
                     "id_modalidad":"",
                     "nombre":"express",
                     "precio":"100",
                     "fecha_inicio":"10/25/2017",
                     "fecha_fin":"10/29/2017",
                     "disponibilidad":10
                  }
               ]
            }
         ]
      },
      {
         "id_ciudad":"4",
         "nombre_ciudad":"CALAMA",
         "latitud":"-22.4568416",
         "longitud":"-68.9335852",
         "cota":"2256",
         "cursos":[
            {
               "id_curso":"",
               "id_categoria":"",
               "nombre":"",
               "fecha_inicio":"",
               "requisitos":"",
               "modalidad":[
                  {
                     "id_modalidad":"",
                     "nombre":"express",
                     "precio":"100",
                     "fecha_inicio":"10/25/2017",
                     "fecha_fin":"11/28/2017",
                     "disponibilidad":10
                  }
               ]
            }
         ]
      },
      {
         "id_ciudad":"2",
         "nombre_ciudad":"ILLAPEL",
         "latitud":"-31.633353",
         "longitud":"-71.1666378",
         "cota":"314",
         "cursos":[
            {
               "id_curso":"1",
               "id_categoria":"1",
               "nombre":"Conducción de Vehículos Particulares",
               "requisitos":"Cedula, mayor de edad, vehiculo particular",
               "modalidad":[
                  {
                     "id_modalidad":"1",
                     "nombre":"Tramo Alto",
                     "precio":"100",
                     "fecha_inicio":"10/25/2017",
                     "fecha_fin":"11/07/2017",
                     "disponibilidad":20
                  }
               ]
            },
            {
               "id_curso":"2",
               "id_categoria":"2",
               "nombre":"Conducción Profesional Pasajeros Menor (A2)",
               "requisitos":"Cedula, mayor de edad, vehiculo A2",
               "modalidad":[
                  {
                     "id_modalidad":"2",
                     "nombre":"Normal",
                     "precio":"221",
                     "fecha_inicio":"10/25/2017",
                     "fecha_fin":"12/27/2017",
                     "disponibilidad":10
                  }
               ]
            },
            {
               "id_curso":"3",
               "id_categoria":"2",
               "nombre":"Conducción Profesional Pasajeros Mayor (A3)",
               "requisitos":"Cedula, mayor de edad, vehiculo A3",
               "modalidad":[
                  {
                     "id_modalidad":"3",
                     "nombre":"Normal",
                     "precio":"221",
                     "fecha_inicio":"10/25/2017",
                     "fecha_fin":"11/27/2017",
                     "disponibilidad":10
                  }
               ]
            },
            {
               "id_curso":"4",
               "id_categoria":"2",
               "nombre":"Conducción Profesional Pasajeros Menor (A2) + Conduccion Profesional Carga Menor (A4)",
               "requisitos":"Cedula, mayor de edad, vehiculo A3",
               "modalidad":[
                  {
                     "id_modalidad":"4",
                     "nombre":"Normal",
                     "precio":"340",
                     "fecha_inicio":"10/22/2017",
                     "fecha_fin":"10/27/2017",
                     "disponibilidad":10
                  }
               ]
            },
            {
               "id_curso":"5",
               "id_categoria":"2",
               "nombre":"Conducción Profesional Pasajeros Mayor (A3) + Conduccion Profesional Carga Mayor (A5)",
               "requisitos":"Cedula, mayor de edad, vehiculo A3",
               "modalidad":[
                  {
                     "id_modalidad":"5",
                     "nombre":"Normal",
                     "precio":"382",
                     "fecha_inicio":"12/25/2017",
                     "fecha_fin":"12/27/2017",
                     "disponibilidad":10
                  },
                   {
                     "id_modalidad":"6",
                     "nombre":"Express",
                     "precio":"455",
                     "fecha_inicio":"12/19/2017",
                     "fecha_fin":"01/05/2018",
                     "disponibilidad":5
                  }
               ]
            }
         ]
      }
   ]
};
	


export {data};